services:
    knp_rad_fixtures_load.loader:
        class: Knp\Rad\FixturesLoad\Loader
        arguments:
            - @doctrine
            - @knp_rad_fixtures_load.fixtures_factory
            - @event_dispatcher

    knp_rad_fixtures_load.fixtures_factory:
        class: Knp\Rad\FixturesLoad\FixturesFactory

    knp_rad_fixtures_load.reset_schema_processor:
        class: Knp\Rad\FixturesLoad\ResetSchemaProcessor
        arguments:
            - @doctrine.orm.entity_manager
            - @knp_rad_fixtures_load.schema_tool

    knp_rad_fixtures_load.schema_tool:
        class: Doctrine\ORM\Tools\SchemaTool
        arguments:
            - @doctrine.orm.entity_manager